### ISSUE TITLE
Use full URL instead of only parts of it.

### ISSUE THREAD

**Issue by drawkula** [dillo-browser/dillo-plugin-spartan#1]
https://github.com/dillo-browser/dillo-plugin-spartan/blob/master/spartan.filter.dpi#L90

May I suggest to use `$url` there instead of the URL having only stripped the scheme name?

**Comment by rodarima** [comment]
Why so? That would cause most of the tab space to be used by the scheme:

![image](https://github.com/dillo-browser/dillo-plugin-spartan/assets/3866127/0b055514-3406-4d2f-a453-adfd238ffbc0)

Maybe a better solution is to extract the first heading text an use as title?

>  CMS-style tools automatically generating menus or Atom/RSS feeds for a directory of text/gemini files can use the first heading in the file as a human-friendly title.

**Comment by rodarima** [comment]
![image](https://github.com/dillo-browser/dillo-plugin-spartan/assets/3866127/e0dc0eb3-9fc2-4495-8d68-651ff602b4a2)

**Comment by drawkula** [comment]
URL without scheme makes the fewest sense.

Full URL would help where no title or other heading can be located.  Additionally in some cases the same text is available e.g. via HTTP(S) and NEX, so I'd prefer to see the difference, which only would be in the protocol.

The full URL is an exact identifier.  "My home page" is found thousands of times in the nets.

But ok.  I can run local forks if it hits me too hard...

**Comment by rodarima** [comment]
> Full URL would help where no title or other heading can be located. Additionally in some cases the same text is available e.g. via HTTP(S) and NEX, so I'd prefer to see the difference, which only would be in the protocol.

If you prefer to see the URL maybe we can address it on the browser with a configuration option, so you can set the tab label (and maybe the window title too) to always show the full URL instead of the page title. Otherwise, it will only be fixed for the spartan plugin.

**Comment by drawkula** [comment]
The window title triggered this for me, not the tabs.  The URL being known in the browser first, even before a converted page is sent back by a plugin, is the best place to make this configurable.  Maybe even for window title and tabs independently if that make even more sense for others?

That idea can ferment a bit, it is not urgent.

There'll be things of higher priority for 3.1-release.
